query getWatchedMovies($userId: String!) @auth(level: USER) {
  watches(where: { user: { id: { eq: $userId } } }) {
    movie {
      id
      title
      description
      imageUrl
      externalId
    }
  }
}
query getTopRatedMovies @auth(level: USER) {
  movies(limit: 10, orderBy: [{ rating: DESC }]) {
    id
    title
    description
    imageUrl
  }
}

query getMostRecent @auth(level: USER) {
  movies(limit: 10, orderBy: [{ releaseYear: DESC }]) {
    id
    title
    description
    imageUrl
  }
}