name: movie_app_fluttercon25
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  firebase_auth: ^5.6.0
  flutter:
    sdk: flutter
  go_router: ^15.2.3
  google_sign_in: ^6.2.2
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
assets:

flutter:
  uses-material-design: true
  assets:
    - lib/static/movies.json
    - lib/static/reeltime_logo.png
