extend type Movie {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Movie", purpose: IMPLICIT_KEY_FIELD)
}
extend type WatchedMovie {
  """
  ✨ Implicit foreign key field based on `WatchedMovie`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String! @fdc_generated(from: "WatchedMovie.user", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `WatchedMovie`.`movie`. It must match the value of `Movie`.`id`. See `@ref` for how to customize it.
  """
  movieId: UUID! @fdc_generated(from: "WatchedMovie.movie", purpose: IMPLICIT_REF_FIELD)
}
